### ISSUE TITLE
你好，求帮忙

### ISSUE THREAD

**Issue by marcelowu** [andy840119/Grand.Plugin.Payments.NewebPay#3]
https://github.com/matmiranda?tab=repositories
https://github.com/mundipagg/MundiAPI-NetStandard

 这里有几个巴西支付的SDK，你有办法做成grandnode 插件吗，这几个随便做哪个都可以。

**Comment by andy840119** [comment]
1. 如果是`WireCard `，似乎在nopcommerce上有人有做好[plugin](http://www.ikozmik.com/wirecard-plugin)，有源碼的話可以考慮自己魔改。
2. 需要報個價，因為工實在有點多，還有能參考的資源不多
3. 需要開測環境給我

**Comment by marcelowu** [comment]
物流系統 nopcommerce4.2
https://github.com/nopCommerceBrasil/NopBrasil.Plugin.Shipping.Correios
官網文件
https://correios.com.br/enviar-e-receber/ferramentas/calculador-remoto-de-precos-e-prazos/pdf/manual-de-implementacao-do-calculo-remoto-de-precos-e-prazos/at_download/file

報個價

**Comment by andy840119** [comment]
是支付和物流系統都要做嗎？
如果是的話可能需要分開報價
.
另外問一下使用的grandnode版本？
因為gtandnode在4.5版後都變成非同步寫法了
版本不會影響報價

**Comment by marcelowu** [comment]
4.6 新版，先报物流系統，因为我没决定用哪个支付。

**Comment by andy840119** [comment]
了解
那直接email(andy840119@gmail.com)過來詢問報價吧
順便提供能支付的方式
這幾天會算好報價回覆
.
因為是第一次在github上接到案件
所以報價只會根據預計完成工時下去報(小弟我在台灣，工時一天大約600人民幣)
主要工時會落在查資料和測試
如果願意把程式碼公開會有另外折扣。

**Comment by marcelowu** [comment]
https://cws2.correios.com.br/static/swagger/?url=/precoprazoservice/rs/swagger.json#/
国际和巴西国内的api
https://apps.correios.com.br/componentes/home/index.html#/ajuda
文档
